### ISSUE TITLE
✨ PaiGram v4

### ISSUE THREAD

**Issue by karakoo** [PaiGramTeam/PaiGram#149]
## ✨ PaiGram v4

<details open>
  <summary>底层</summary>

- [x] ✨ 集成 [FastApi](https://fastapi.tiangolo.com/zh/)
     - [x] ♻️ 重写 `core`
       - [x] ♻️ 重写 `Service` 的加载方式
       - [x] ♻️ 重写 `Plugin` 的加载方式
     - [ ] ✨ 集成 [`ASGI`](https://asgi.readthedocs.io)
     - [ ] ✨ 支持 [Telegram Web App](https://core.telegram.org/bots/webapps)

</details>

<details open>
  <summary>功能</summary>

- [ ] ✨ [Telegram Web App](https://core.telegram.org/bots/webapps)
  - [ ] ✨ 养成计算器
  - [ ] ✨ 伤害计算器
  - [x] ~~✨ 内嵌米游社登录，从而获取cookie~~

</details>

**Comment by luoshuijs** [comment]
@karakoo WC真写啊

**Comment by zhxycn** [comment]
加一个 #215

**Comment by karakoo** [comment]
todo #169

**Comment by luoshuijs** [comment]
https://github.com/luoshuijs/TGPaimonBot/blob/4dcc1fab476a8d1b30b1e7704b33cb98fdf117e3/core/bot.py#L116
用cast声明类型即可，不需要重写类型

https://github.com/luoshuijs/TGPaimonBot/blob/27cdd95f6febb079781d87ac020f23acad387e86/utils/log/_logger.py#L106
应该改为 `if sekf.config.capture_warnings: `

https://github.com/luoshuijs/TGPaimonBot/blob/27cdd95f6febb079781d87ac020f23acad387e86/utils/log/_config.py#L33
应该改为 `width: Optional[int] = None`，默认自动宽度，除非说明

**Comment by luoshuijs** [comment]
因为 #325 ，需要 `allowed_updates` 传入[所有更新](https://docs.python-telegram-bot.org/en/stable/telegram.update.html#telegram.Update.ALL_TYPES)，其中包括 `chat_member` 更新

V4版本希望能够忽略 `UpdateType.EDITED_CHANNEL_POST` 和 `UpdateType.EDITED_MESSAGE` 即可

**Comment by luoshuijs** [comment]
移除 `@init_service` service 初始化在 `__init__` 上执行。

以解决原使用 `alembic` 导致执行 `init_service` 出现的问题。

以 `UserService` 为例，移除 `user/__init__.py` 后修改 `user.service.UserService.__init__()`

```python3
class UserService(BaseService):
    def __init__(self, mysql: MySQL) -> None:
        self._repository = UserRepository(mysql)
```

并使用 `subclass` 获取全部已经载入的子类，并对其依赖注入后实例化

为避免和原来 `service\base` 冲突，建议重命名为 `dependence`。

**Comment by luoshuijs** [comment]
规范Debug相关输出，切勿直接打印变量。
