### ISSUE TITLE
[Bug]: unknown_command 没有返回「前面的区域，以后再来探索吧！」

### ISSUE THREAD

**Issue by chuangbo** [PaiGramTeam/PaiGram#167]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/luoshuijs/TGPaimonBot/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

28330507d164666f3ba884c400a2963eb316eed2

### 运行环境

MacOS

### 重现步骤

发送不存在的命令比如 /hello

### 期望的结果是什么？

机器人返回「前面的区域，以后再来探索吧！」

### 实际的结果是什么？

无

**Comment by luoshuijs** [comment]
需要注意的是这个命令需要注册到除自己外的命令注册后才能使用
