### ISSUE TITLE
[Feat]: 拆分 `InlineQueryHandler` 并能让每个插件都能注册

### ISSUE THREAD

**Issue by luoshuijs** [PaiGramTeam/PaiGram#169]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/luoshuijs/TGPaimonBot/issues) 以及 [Pull Request](https://github.com/luoshuijs/TGPaimonBot/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

拆分 `InlineQueryHandler` 并能让每个插件都能注册而不需要单独在原来的 `lnline.py` 文件上修改

```python3
@handler.inline()
async def inline_query(self, update: Update, context: CallbackContext, args: List[str]) -> List[InlineQueryResultArticle]:
    pass
```

**Comment by luoshuijs** [comment]
todo+++++++++++

**Comment by omg-xtao** [comment]
已完成
