### ISSUE TITLE
[Feat]: 缓存 html to image

### ISSUE THREAD

**Issue by chuangbo** [PaiGramTeam/PaiGram#189]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/luoshuijs/TGPaimonBot/issues) 以及 [Pull Request](https://github.com/luoshuijs/TGPaimonBot/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

记录一下各位开发者大佬的讨论方案：

### 问题

用户短时间内发送多条重复命令，返回的图片未发生改变。在这样的情况下，希望派蒙可以提高回复速度。

### 方案

* 增加 html to image 缓存
* 增加 utils 对 template_service.render 进行封装，管理缓存逻辑，比如 `render_util.reply_photo(message, template_name, data)`
* cache key 为 html 的 sha256
* cache value 为 reply_photo 后 tg 返回的 file_id
* 存入 redis，并设置合理的 ttl

### 其他备选方案

* template data 为 key，缓存生成图片：数据占用内存过大
* template data 为 key，缓存 file_id：data 可能包含渲染中用不到，但是又已经改变了的数据，比如时间戳，会降低缓存命中率

**Comment by chuangbo** [comment]
试了一下，不修改 render 是不可能的，因为至少要返回 html 的哈希，然后既然都要修改 render，我对封装方案有个新想法，大伙看看够不够简洁易懂

```python
# 原写法
help_png = await self.template_service.render("bot/help/help.html", data)
reply_photo = await message.reply_photo(help_png)

# 支持缓存的写法
help_image = await self.template_service.render("bot/help/help.html", data)
# render 返回 RenderResult，封装 reply_photo, reply_document 等方法，加上缓存管理
await help_image.reply_photo(message)
```

**Comment by luoshuijs** [comment]
@chuangbo Messsge 去哪里了
