### ISSUE TITLE
:sparkles: Add docker integration/支持 Docker 容器化

### ISSUE THREAD

**Issue by Billyzou0741326** [PaiGramTeam/PaiGram#224]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/luoshuijs/TGPaimonBot/issues) 以及 [Pull Request](https://github.com/luoshuijs/TGPaimonBot/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

增加 `Dockerfile` 支持部署docker容器，提高部署效率

本地生成docker镜像：

```shell
# build
docker build . -t TGPaimonBot:latest
# run
docker run --rm --name TGPaimonBot --env-file .env TGPaimonBot:latest
```

可部署到支持docker的平台，如 Google Cloud Run, Amazon ECS, Heroku 等，以 environment variables (`--env` 或 `--env-file`) 的方式传入数据库参数以及其它相关配置。

**Comment by ProblemFactory** [comment]
1. 在目前的Docker file里所用的python:3.10.8-slim-bullseye已经不存在，建议使用python:3.10-slim-bullseye
2. 希望可以在README中加入Docker部署教程，以及利用Action自动生成映像文件并上传到DockerHub。

**Comment by luoshuijs** [comment]
> 1. 在目前的Docker file里所用的python:3.10.8-slim-bullseye已经不存在，建议使用python:3.10-slim-bullseye
> 2. 希望可以在README中加入Docker部署教程，以及利用Action自动生成映像文件并上传到DockerHub。

这些问题会在 #383 完成后一并修复
