### ISSUE TITLE
[Bug]: 导入UIGF格式的抽卡记录显示文件太大

### ISSUE THREAD

**Issue by ProblemFactory** [PaiGramTeam/PaiGram#421]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

最新DockerHub版

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

从我本地的Genshin-Wish-Export导出UIGF格式的祈愿记录，然后发送给派蒙机器人，用/gacha_log_import回复发送的文件。

### 期望的结果是什么？

成功导入祈愿记录

### 实际的结果是什么？

提示“文件过大，请发送小于 2 MB 的文件”

### 补充说明（可选）

我的祈愿记录的JSON文件有2.50 MB

**Comment by luoshuijs** [comment]
刚刚改了文件上限，测试了20MB的文件，直接堵塞了。
目前默认的还是2MB限制，如果是自用的话请改配置文件调整文件。

**Comment by luoshuijs** [comment]
已经使用新办法解决，不久后调整文件上限

**Comment by luoshuijs** [comment]
已更新
