### ISSUE TITLE
[Feat]: /player_card指令在选择角色时将placeholder图像换成当前可选角色的基本信息

### ISSUE THREAD

**Issue by ProblemFactory** [PaiGramTeam/PaiGram#442]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 以及 [Pull Request](https://github.com/PaiGramTeam/PaiGram/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

类似于yunzaibot的`#更新面板`返回的图片，展示当前可选角色的等级，命座等基本信息。

**Comment by luoshuijs** [comment]
嗯可以考虑，但是我打算在V4再添加这个功能，现在我们大部分精力都在重构上了。

**Comment by luoshuijs** [comment]
目前我们这边的开发者非常不够（~~指看得懂V4代码核心功能只有我和另外一个贡献者看得懂，其他人都在摸鱼~~），V4进度已经卡了1个月了。如果可以的话欢迎大佬加入我们的贡献中，具体问题也可以通过我 Github 个人主页任何一个连接私聊到我。
顺便一提具体进度可在 [Project](https://github.com/orgs/PaiGramTeam/projects/3) 中见到。

**Comment by luoshuijs** [comment]
已经有贡献者打开 pull request。不过提醒的是，后续更新和查询命令会分开，不然又要请求又要 io 操作又要合成更新图片，导致角色卡片发送时速度变慢。
