### ISSUE TITLE
[Bug]: pytest-asyncio 0.22.0  has been yanked

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/PaiGram#682]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

e00cf57e60dc0254de781c20af0b3075324442f8

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

docker compose build

### 期望的结果是什么？

no error

### 实际的结果是什么？

65.67 Because paigram depends on pytest-asyncio (^0.22.0) which doesn't match any versions, version solving failed.

### 补充说明（可选）

https://pypi.org/project/pytest-asyncio/0.22.0/

This release has been yanked

**Comment by omg-xtao** [comment]
fixed. You can use
```
git fetch --all
git reset --hard origin/main
```
