### ISSUE TITLE
[Bug]: CMD strategy  timeout

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/PaiGram#683]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

fca5338297d237e2098204a490b9155dd76dbd96

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

/strategy 刻晴

### 期望的结果是什么？

no error

### 实际的结果是什么？

```
paigram-paimon-1  | [2023-11-03 20:34:13] WARNING  Httpx [ReadTimeout]                                                                   plugins.system.errorhandler 231  
paigram-paimon-1  |                                GET[https://upload-bbs.miyoushe.com/upload/2023/04/01/74019947/22340ae02c39714976136d                                  
paigram-paimon-1  |                                015d204e6d_1558373498547692434.png]                                                                                    
paigram-paimon-1  |                       INFO     尝试通知用户 abc[1234] 错误信息[出错了呜呜呜 ~  服务器熟啦 ~ 请稍后再试]    plugins.system.errorhandler 98   
```

### 补充说明（可选）

Maybe it's slower to access Miyoushe from a foreign server.

**Comment by luoshuijs** [comment]
如果服务器部署在海外会出现访问超时问题，这个属于网络问题，可以考虑把 timeout 参数设置的更大一些
If the server is deployed overseas, there may be issues with access timeouts. This is a network problem, and you might consider setting the timeout parameter to a larger value.

**Comment by lostsnow** [comment]
```
$ time curl -sS https://upload-bbs.miyoushe.com/upload/2023/04/01/74019947/22340ae02c39714976136d015d204e6d_1558373498547692434.png > a.png
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

real	1m14.596s
user	0m0.077s
sys	0m0.005s
```
It's so sad....

**Comment by luoshuijs** [comment]
好像还有个问题...刚刚前瞻直播结束，估计现在网络在海外请求拥堵似乎也是一件意料之内的事情（？）
It seems there's another issue... The preview live stream just ended, and it's probably expected that the internet is congested with overseas requests right now.(?)
