### ISSUE TITLE
今日素材表

### ISSUE THREAD

**Issue by heeler-deer** [PaiGramTeam/PaiGram#74]
加入今日素材表能够丰富该bot的功能,对于我这种懒人还是很有必要的(
类似于https://genshin.pub/daily

**Comment by luoshuijs** [comment]
最近有点事情估计还咕咕很久，现在V2版本（即现在main分支）还没重构完成，~目测下下个月前先把HTML写完。~

**Comment by luoshuijs** [comment]
@heeler-deer 关于今日素材表，是打算显示全部还是你所拥有的角色
考虑到前者图片会随着开放其他国家越来越大，可能导致图片太大显示模糊，后者需要  `Cookies`  查询，两边都是有问题
后者还有个限制就是武器素材只能获取你武器所装备的角色

**Comment by heeler-deer** [comment]
> @heeler-deer 关于今日素材表，是打算显示全部还是你所拥有的角色 考虑到前者图片会随着开放其他国家越来越大，可能导致图片太大显示模糊，后者需要 `Cookies` 查询，两边都是有问题 后者还有个限制就是武器素材只能获取你武器所装备的角色

 我确实没想那么多，因为我看[genshin.pub](https://genshin.pub/daily)的今日素材表觉得很有用就来提issue了(

目前[genshin.pub](https://genshin.pub/daily)的做法是展示全部的素材，这样图片确实会随着国家的逐步开放变大模糊，我认为确实不适合该项目。
或许可以按照地区划分，比如查询蒙德的今日素材，上面显示蒙德的素材以及素材对应的人物、武器，这样一来图片大小基本确定，二来不需要cookie
缺点似乎在于玩家在看素材表时不会去专门想到去看特定地区的素材而是全部地区的素材？

**Comment by luoshuijs** [comment]
按照区域划分，这也不是不行的办法，有个问题就是请求的时候得询问玩家你要查看那个地区的

**Comment by luoshuijs** [comment]
@heeler-deer 根据Pr这边的意思目前安排的是需要 `Cookies` 查询自己所拥有的素材，如果有啥意见可以说明或查看Pr代码

**Comment by karakoo** [comment]
@luoshuijs
