### ISSUE TITLE
[Bug]: GramCore commit 6d1e8bcc497ed255e581b5e47de88e01cdef98f7 not exists

### ISSUE THREAD

**Issue by lostsnow** [PaiGramTeam/PaiGram#743]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/PaiGramTeam/PaiGram/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 程序版本 （Commit Id）

4e84a76464abb8e90dbac4bf3ed2546b83fa618f

### 运行环境

Ubuntu

### 运行架构

AMD64

### 重现步骤

This commit https://github.com/PaiGramTeam/PaiGram/commit/4e84a76464abb8e90dbac4bf3ed2546b83fa618f change GramCore to 
https://github.com/PaiGramTeam/GramCore/tree/6d1e8bcc497ed255e581b5e47de88e01cdef98f7, but it's a non-existent commit

### 期望的结果是什么？

200

### 实际的结果是什么？

404

**Comment by omg-xtao** [comment]
I'm so sorry. I forgot to push.
