### ISSUE TITLE
“武器查询”功能失效

### ISSUE THREAD

**Issue by karakoo** [PaiGramTeam/PaiGram#75]
爬取武器数据的爬虫已经不适用于新版的 [Honey Impact](https://genshin.honeyhunterworld.com/) 页面

https://github.com/luoshuijs/TGPaimonBot/blob/ea81cdb5267aa993de731d8ef5f35c0ba0a3c64b/models/wiki/weapons.py#L30

https://github.com/luoshuijs/TGPaimonBot/blob/ea81cdb5267aa993de731d8ef5f35c0ba0a3c64b/models/wiki/weapons.py#L63-L77

**Comment by zhxycn** [comment]
建议直接把数据写进json放本地

**Comment by karakoo** [comment]
> 建议直接把数据写进json放本地

目前是把数据写进的redis，差别不大

**Comment by luoshuijs** [comment]
反正都得解析JSON
